"""
stat_contracts_loader.py -- read-side of the ONE statistical contract registry (master plan §6).

The registry (`scripts/sota_recon/witness_gate/contracts/stat_contracts.v1.json`, generated by
`scripts/sota_recon/witness_gate/build_stat_contracts.py`) is the single source of truth for
aggregation semantics: which columns are recomputed rates (and from which components), which are
volume-weighted, which are single-play maxima, which season cells are fact-adjusted witness-direct,
and which columns are non-additive. The generator proves parity against the pre-switch literal
sets before writing, so consumers loading from here are behavior-identical to the old inline sets.

Consumers: aggregate_nfl_stats_fly.py (season/career builder) and scripts/sota_recon/
recon_aggregate.py (season/career validation lane). Do NOT re-declare these sets locally --
that fragmentation is exactly what the registry closed (SOTA master plan §6, executed 2026-07-25).
"""
from __future__ import annotations

import json
import os
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

_REL = Path("scripts") / "sota_recon" / "witness_gate" / "contracts" / "stat_contracts.v1.json"


def registry_path() -> Path:
    """Resolve the committed registry JSON: env override, then repo-root search upward."""
    env = os.environ.get("STAT_CONTRACTS_PATH")
    if env:
        return Path(env)
    here = Path(__file__).resolve()
    for parent in here.parents:
        cand = parent / _REL
        if cand.is_file():
            return cand
    raise FileNotFoundError(
        f"stat_contracts.v1.json not found above {here}; expected <repo>/{_REL} "
        "(regenerate with `python -m scripts.sota_recon.witness_gate.build_stat_contracts` "
        "or point STAT_CONTRACTS_PATH at it)"
    )


@lru_cache(maxsize=1)
def load_registry() -> dict:
    with open(registry_path(), "r", encoding="utf-8") as fh:
        return json.load(fh)


@dataclass(frozen=True)
class AggregationSets:
    per_game_avg_cols: dict[str, str]
    derived_rate_cols: set[str]
    derived_rate_dependencies: dict[str, tuple[str, ...]]
    share_family_cols: set[str]
    weighted_avg_cols: dict[str, str]
    max_cols: set[str]
    fact_adjusted_season_cols: set[str]
    non_additive_exact: set[str]
    non_additive_prefixes: tuple[str, ...]


@lru_cache(maxsize=1)
def aggregation_sets() -> AggregationSets:
    s = load_registry()["aggregation_sets"]
    # ONE SOURCE OF TRUTH FOR "IS THIS A MAX COLUMN", DERIVED FROM THE DECLARED CLASS.
    #
    # This file held the fact TWICE and the two copies drifted. `aggregation_sets.max_cols`
    # was a hand-maintained list of 4 (fg_long, passing_long, receiving_long, rushing_long)
    # while `stats[].aggregation_class == "MAX"` declared 7 -- the same 4 plus
    # kickoff_return_long, punt_long and punt_return_long. The aggregator reads the hand
    # list, so those three were SUMMED into the season and career tables.
    #
    # The damage was not subtle and it shipped: on rows where weekly MAX != weekly SUM, the
    # stored season value equalled SUM on 100% and MAX on 0% (1,720 / 1,916 / 1,086 rows),
    # leaving 4,407 stored "long" values above 100 yards -- a 342-yard kickoff return, an
    # 875-yard punt. The four columns that WERE on the hand list aggregated correctly, which
    # is what proves this is the drift and not a MAX bug.
    #
    # Deriving costs nothing and cannot drift. A column declared MAX is now MAXed, full stop.
    declared_max = {row["stat_id"] for row in load_registry()["stats"]
                    if row.get("aggregation_class") == "MAX"}
    return AggregationSets(
        per_game_avg_cols=dict(s["per_game_avg_cols"]),
        derived_rate_cols=set(s["derived_rate_cols"]),
        derived_rate_dependencies={k: tuple(v) for k, v in s["derived_rate_dependencies"].items()},
        share_family_cols=set(s["share_family_cols"]),
        weighted_avg_cols=dict(s["weighted_avg_cols"]),
        max_cols=declared_max,
        fact_adjusted_season_cols=set(s["fact_adjusted_season_cols"]),
        non_additive_exact=set(s["non_additive_exact"]),
        non_additive_prefixes=tuple(s["non_additive_prefixes"]),
    )


@lru_cache(maxsize=1)
def contract_classes() -> dict[str, tuple[str, str]]:
    """stat_id -> (aggregation_class, season_derivation) for every contracted column."""
    return {row["stat_id"]: (row["aggregation_class"], row.get("season_derivation", "none"))
            for row in load_registry()["stats"]}


def non_sum_stat_ids() -> set[str]:
    """Columns whose contract says they are NOT plain additive SUM aggregates (rates, maxima,
    weighted recomputes, context/identity, cardinality counts). Validation lanes use this so a
    rate column can never be held to a season==SUM(weekly) expectation (the legacy exclusion
    sets missed e.g. the NY/A / AY/A / ANY/A trio -- 1,366 false career mismatches)."""
    return {sid for sid, (agg, _der) in contract_classes().items() if agg != "SUM"}


def contract_for(stat_id: str) -> dict | None:
    """Full contract row for one canonical column (None if not contracted)."""
    reg = load_registry()
    index = getattr(contract_for, "_index", None)
    if index is None:
        index = {row["stat_id"]: row for row in reg["stats"]}
        contract_for._index = index
    return index.get(stat_id)
