"""Generate the frontend's canonical league-settings scoring key manifest."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Iterable

from multi_league.core.canonical_settings import ALL_SCORING_KEYS


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = REPO_ROOT / "frontend" / "src" / "generated" / "player-scoring-ddl-keys.ts"


def render_manifest(keys: Iterable[str]) -> str:
    ordered_keys = list(keys)
    lines = [
        "// AUTO-GENERATED by scripts/generate_player_scoring_ddl_manifest.py.",
        "// Edit multi_league.core.canonical_settings.ALL_SCORING_KEYS, then regenerate.",
        "",
        "export const CANONICAL_SCORING_DDL_KEYS = [",
    ]
    lines.extend(f'  "{key}",' for key in ordered_keys)
    lines.extend([
        "] as const;",
        "",
        "export type CanonicalScoringDdlKey = (typeof CANONICAL_SCORING_DDL_KEYS)[number];",
        "",
    ])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_manifest(ALL_SCORING_KEYS), encoding="utf-8")


if __name__ == "__main__":
    main()
